stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    params:
      - epochs
    plots:
      - expref/plots:
          cache: false
    metrics:
      - expref/metrics.json:
          cache: false

  usage-commands:
    cmd: python commands.py
    params:
      - epochs
    plots:
      - usage/plots:
          cache: false
    metrics:
      - usage/metrics.json:
          cache: false

  system-os:
    cmd: python system.py
    params:
      - epochs
    plots:
      - system/plots:
          cache: false
    metrics:
      - system/metrics.json:
          cache: false
