stages:
  test-dvclive:
    cmd: python train.py
    params:
      - epochs
    plots:
      - dvclive/plots:
          cache: false
    metrics:
      - dvclive/metrics.json:
          cache: false

  usage-commands:
    cmd: python commands.py
    params:
      - epochs
    plots:
      - usage/plots:
          cache: false
    metrics:
      - usage/metrics.json:
          cache: false

  system-os:
    cmd: python system.py
    params:
      - epochs
    plots:
      - system/plots:
          cache: false
    metrics:
      - system/metrics.json:
          cache: false
  exp:
      cmd: python exp.py
      deps:
        - exp.py
      params:
        - epochs
      plots:
        - exp/plots:
            cache: false
      metrics:
        - exp/metrics.json:
            cache: false
